services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src/models:/app/src/models
      - ./.dvc:/app/.dvc
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow 
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns