services:
  mlflow:
      build:
        context: .
        dockerfile: Dockerfile.mlflow
      command: >
        mlflow server
        --host 0.0.0.0
        --backend-store-uri sqlite:///mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
        --serve-artifacts
        --gunicorn-opts "--log-level debug"
      ports:
        - "5000:5000"
      volumes:
        - ./mlruns:/mlflow:rw
      env_file: .env
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5000
      restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
      - ./src/models:/app/src/models:rw
      - ./.dvc:/app/.dvc:rw
      - ./.dvc/cache:/app/.dvc/cache:rw
      - ./mlruns:/mlflow:rw
    env_file: .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    restart: unless-stopped

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    user: "1000:0"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./airflow/airflow.db:/opt/airflow/airflow.db
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/project:z
      - ./data:/opt/airflow/project/data:rw
      - ./.dvc:/opt/airflow/project/.dvc:rw
      - ./mlruns:/mlflow:rw
      - /tmp/dvc_cache:/opt/airflow/project/.dvc/cache:rw
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password password --firstname Admin --lastname User --role Admin --email admin@example.com
      "

  airflow-webserver:
    user: "1000:0"
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DVC_STORAGE_PATH=/opt/airflow/project/data
      - DVC_CACHE_DIR=/tmp/dvc_cache
    volumes:
      - ./airflow/airflow.db:/opt/airflow/airflow.db
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/project:z
      - ./data:/opt/airflow/project/data:rw
      - ./.dvc:/opt/airflow/project/.dvc:rw
      - ./mlruns:/mlflow:rw
      - /tmp/dvc_cache:/opt/airflow/project/.dvc/cache:rw
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - airflow-scheduler
    command: airflow webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    user: "1000:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/airflow.db:/opt/airflow/airflow.db
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/project:z
      - ./data:/opt/airflow/project/data:rw
      - ./.dvc:/opt/airflow/project/.dvc:rw
      - ./mlruns:/mlflow:rw
      - /tmp/dvc_cache:/opt/airflow/project/.dvc/cache:rw
    depends_on:
      - airflow-init
    command: airflow scheduler