FROM apache/airflow:2.7.1

USER root

RUN mkdir -p /opt/airflow/logs/{scheduler,webserver,dag_processor_manager} && \
    chown -R airflow:root /opt/airflow && \
    chmod -R 775 /opt/airflow/logs

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git && \
    rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir --user \
    mlflow==2.9.2 \
    pydantic==1.10.13 \
    scikit-learn==1.3.2 \
    pandas==2.0.3 \
    dvc==3.41.0