FROM apache/airflow:2.7.1

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git && \
    rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --user \
    mlflow==2.9.2 \         
    pydantic==1.10.13 \  
    scikit-learn==1.3.2 \
    pandas==2.0.3 \
    dvc==3.41.0