stages:
  import_data:
    cmd: python src/data/import_raw_data.py
    outs:
      - data/raw/
    deps:
      - src/data/import_raw_data.py

  preprocess:
    cmd: python src/data/make_dataset.py ./data/raw ./data/preprocessed
    deps:
      - src/data/make_dataset.py
      - data/raw/
    outs:
      - data/preprocessed/X_test.csv
      - data/preprocessed/y_test.csv

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/preprocessed
    outs:
      - src/models/trained_model.joblib

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/trained_model.joblib
      - data/preprocessed/X_test.csv
      - data/preprocessed/y_test.csv
    outs:
      - src/models/prod_model.joblib

  predict:
    cmd: python src/models/predict_model.py src/models/test_features.json
    deps:
      - src/models/predict_model.py
      - src/models/prod_model.joblib
      - src/models/test_features.json